import { NextRequest, NextResponse } from "next/server";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  BorderStyle,
} from "docx";

/**
 * POST /api/export-cover-letter
 *
 * Generates a properly formatted .docx cover letter.
 * Accepts structured data and returns a binary Word document.
 */
export async function POST(request: NextRequest) {
  try {
    const {
      paragraphs,   // string[] — the AI-generated body paragraphs
      name,         // applicant full name
      email,
      phone,
      city,
      province,
      linkedin,
      jobTitle,
      company,
    } = await request.json();

    if (!paragraphs || !Array.isArray(paragraphs) || paragraphs.length === 0) {
      return NextResponse.json({ error: "paragraphs array required" }, { status: 400 });
    }

    const fullName = name || "Applicant";
    const today    = new Date().toLocaleDateString("en-US", {
      year: "numeric", month: "long", day: "numeric",
    });

    // ── Build contact line ───────────────────────────────────────────────
    const contactParts: string[] = [];
    if (email)    contactParts.push(email);
    if (phone)    contactParts.push(phone);
    if (city && province) contactParts.push(`${city}, ${province}`);
    else if (city) contactParts.push(city);
    if (linkedin) contactParts.push(linkedin.replace(/^https?:\/\/(www\.)?/i, ""));
    const contactLine = contactParts.join("  |  ");

    // ── Reusable style helpers ───────────────────────────────────────────
    const FONT     = "Calibri";
    const BODY_SZ  = 22;   // half-points (11pt)
    const NAME_SZ  = 32;   // 16pt
    const HEADING_SZ = 24; // 12pt

    const bodyPara = (text: string, spacingBefore = 0, spacingAfter = 160): Paragraph =>
      new Paragraph({
        spacing: { before: spacingBefore, after: spacingAfter },
        children: [
          new TextRun({ text, font: FONT, size: BODY_SZ }),
        ],
      });

    const blankLine = (): Paragraph =>
      new Paragraph({
        spacing: { before: 0, after: 0 },
        children: [new TextRun({ text: "", font: FONT, size: BODY_SZ })],
      });

    // ── Document sections ────────────────────────────────────────────────
    const children: Paragraph[] = [

      // ① Full name — large, bold
      new Paragraph({
        spacing: { before: 0, after: 60 },
        children: [
          new TextRun({
            text: fullName,
            bold: true,
            font: FONT,
            size: NAME_SZ,
            color: "2D3A8C",   // indigo
          }),
        ],
      }),

      // ② Contact info
      new Paragraph({
        spacing: { before: 0, after: 320 },
        children: [
          new TextRun({ text: contactLine, font: FONT, size: 18, color: "6B7280" }),
        ],
        border: {
          bottom: { style: BorderStyle.SINGLE, size: 6, color: "E5E7EB" },
        },
      }),

      blankLine(),

      // ③ Date
      bodyPara(today, 0, 240),

      blankLine(),

      // ④ Salutation
      bodyPara(`Dear Hiring Manager,`, 0, 200),

      // ⑤ Body paragraphs
      ...paragraphs.map((p: string) => bodyPara(p, 0, 200)),

      // ⑥ Sign-off
      bodyPara("Sincerely,", 200, 80),
      bodyPara(fullName, 0, 0),

    ];

    // ── Compose document ─────────────────────────────────────────────────
    const doc = new Document({
      creator:     "AutoApply AI",
      title:       `Cover Letter — ${jobTitle || "Application"} at ${company || ""}`.trim(),
      description: `AI-tailored cover letter generated by AutoApply AI`,
      styles: {
        default: {
          document: {
            run: { font: FONT, size: BODY_SZ },
          },
        },
      },
      sections: [
        {
          properties: {
            page: {
              margin: { top: 900, bottom: 900, left: 1080, right: 1080 },
            },
          },
          children,
        },
      ],
    });

    const buffer = await Packer.toBuffer(doc);

    const safeCompany  = (company  || "Company").replace(/[^a-zA-Z0-9 _-]/g, "").trim().slice(0, 30);
    const safeTitle    = (jobTitle || "Role").replace(/[^a-zA-Z0-9 _-]/g, "").trim().slice(0, 30);
    const filename     = `Cover_Letter_${safeCompany}_${safeTitle}.docx`
      .replace(/\s+/g, "_");

    return new NextResponse(new Uint8Array(buffer), {
      status: 200,
      headers: {
        "Content-Type":        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "Content-Disposition": `attachment; filename="${filename}"`,
        "Content-Length":      buffer.byteLength.toString(),
      },
    });
  } catch (err) {
    console.error("export-cover-letter error:", err);
    return NextResponse.json(
      { error: err instanceof Error ? err.message : "Export failed" },
      { status: 500 }
    );
  }
}
